doc/TDesignBlazor.Docs.Shared/Layouts/NavMenu.razor, doc/TDesignBlazor.Docs.Shared/Pages/Components/ButtonPage.razor, doc/TDesignBlazor.Docs.Shared/Pages/Components/LoadingPage.razor, src/TDesignBlazor/Components/Button.cs, src/TDesignBlazor/Components/Loading/Loading.cs, src/TDesignBlazor/Components/Loading/LoadingContainer.cs
* `Loading` 组件 #5 
* 修复按钮的 Disabled 为 `false` 依然不可点击的问题
=> Loading 组件

readme.md
=> 更新首页的 readme 文档

doc/TDesignBlazor.Docs.Shared/Pages/Startup/Index.razor, readme.md, src/TDesignBlazor/TDesignBlazor.csproj
> 非常感谢您对本项目的贡献，所有的合并请求最终将由作者通过才可以合并成功。并且要求贡献者需要谦虚地对待每一次评审的内容，并且尊重每一位贡献者的回复。
- 必要的单元测试已经完成
- 完成必要的注释，包括参数、方法、属性、类等
- 代码风格必须符合 C# 的代码规范
> 其他描述写在这里
ISSUE 编号：
由于包名称 TDesign 被占用，改为 TDesignBlazor 作为包名称
使用 `@名字`来提及你期望参与本次评审人成员 
> **再次感谢贡献者的辛苦付出，良好的规范才能让项目健康的运转，保持利他精神才是我们一直信奉的价值观。**
=> 由于 package id 被占用，改为 TDesignBlazor

TDesignBlazor.sln, src/TDesignBlazor.Test/Components/LinkTest.cs
> 非常感谢您对本项目的贡献，所有的合并请求最终将由作者通过才可以合并成功。并且要求贡献者需要谦虚地对待每一次评审的内容，并且尊重每一位贡献者的回复。
- 必要的单元测试已经完成
- 完成必要的注释，包括参数、方法、属性、类等
- 代码风格必须符合 C# 的代码规范
- [X ] DevOps （CI/CD、git action 等）
> 其他描述写在这里
ISSUE 编号：
Link 组件的单元测试
使用 `@名字`来提及你期望参与本次评审人成员 
如果有，请写明
> **再次感谢贡献者的辛苦付出，良好的规范才能让项目健康的运转，保持利他精神才是我们一直信奉的价值观。**
=> Link 的单元测试

TDesignBlazor.sln, src/TDesignBlazor.Test/Components/ButtonTest.cs, src/TDesignBlazor.Test/Components/IconTest.cs, src/TDesignBlazor.Test/Components/LinkTest.cs, src/TDesignBlazor.Test/TDesignBlazor.Test.csproj, src/TDesignBlazor.Test/TestBase.cs, src/TDesignBlazor.Test/Usings.cs, src/TDesignBlazor/Components/Button.cs, src/TDesignBlazor/TDesignBlazor.csproj
> 非常感谢您对本项目的贡献，所有的合并请求最终将由作者通过才可以合并成功。并且要求贡献者需要谦虚地对待每一次评审的内容，并且尊重每一位贡献者的回复。
- 必要的单元测试已经完成
- 完成必要的注释，包括参数、方法、属性、类等
- 代码风格必须符合 C# 的代码规范
> 其他描述写在这里
ISSUE 编号：#112 
目前所有组件的单元测试
使用 `@名字`来提及你期望参与本次评审人成员 
如果有，请写明
> **再次感谢贡献者的辛苦付出，良好的规范才能让项目健康的运转，保持利他精神才是我们一直信奉的价值观。**
=> 【测试】Button 组件的单元测试代码

readme.md, src/TDesignBlazor.Test/Components/DividerTest.cs, src/TDesignBlazor.Test/TestBase.cs, src/TDesignBlazor/Components/Divider.cs
=> 【新增】Divider 组件的单元测试

src/TDesignBlazor.Test/Components/AvatarTest.cs, src/TDesignBlazor.Test/TestBase.cs
=> 【新增】Avatar 和 AvatarGroup 单元测试

src/TDesignBlazor.Test/Components/BadgeTest.cs, src/TDesignBlazor/Components/Badge.cs
【修复】Badge 的 ChildContent 样式 badge-block 写错成 badge-black 的问题
* 【新增】Badge 组件的单元测试
* 【修复】Badge 的 `ChildContent` 样式 `badge-block` 写错成 `badge-black` 的问题
> 其他描述写在这里
ISSUE 编号：
=> 【新增】Badge 组件的单元测试并修复了样式错误的 bug

src/TDesignBlazor.Test/Components/BreadcrumbTest.cs, src/TDesignBlazor/Components/Breadcrumb/BreadcrumbItem.cs
* 【新增】Breadcrumb 的单元测试
*  【修复】BreadcrumbItem 根据 `Link` 参数渲染 HTML 元素错误问题
> 其他描述写在这里
ISSUE 编号：
=> 【新增】Breadcrumb 的单元测试

src/TDesignBlazor.Test/Components/SpaceTest.cs
=> 【新增】Space 和 SpaceItem 组件的单元测试

src/TDesignBlazor.Test/Components/ButtonTest.cs
>标题格式：【更新】修改了编码格式，已约定统一使用 `UTF8 With Bom` 编码
> 将 `ButtonTest.cs` 文件的编码格式改为 `UTF8 With Bom` ，已约定统一使用 `UTF8 With Bom` 编码
> 文件编码格式改为 `UTF8 With Bom` 
ISSUE 编号：
=> 修改了编码格式，已约定统一使用UTF8 With Bom编码

doc/TDesign.Docs.Shared/Components/HighlightAlert.razor, doc/TDesign.Docs.Shared/Layouts/NavMenu.razor, doc/TDesign.Docs.Shared/Pages/Components/InputAdornmentPage.razor, src/TDesign.Test/Components/InputAdornmentTest.cs, src/TDesign.Test/TDesign.Test.csproj, src/TDesign/Components/Forms/TInputAdornment.cs
【新增】InputAdornment 组件
【新增】InputAdornment 组件的单元测试
> 其他描述写在这里
ISSUE 编号： #36 
=> 【新增】InputAdornment 组件

readme.md
* 徽章链接
* 静态站点链接
> 其他描述写在这里
ISSUE 编号：
=> 【更新】首页 readme 链接错误

doc/TDesign.Docs.Shared/Components/Example.razor, doc/TDesign.Docs.Shared/Layouts/MainLayout.razor
>标题格式：【修复】文档简单样式
> example 预览示例代码 icon 居中，menu 官网 hover 效果
> 其他描述写在这里
ISSUE 编号：
=> 【修复】文档简单样式

.github/workflows/pull-request.yml, doc/TDesign.Docs.Shared/Layouts/NavMenu.razor, doc/TDesign.Docs.Shared/Pages/Components/CommentPage.razor, src/TDesign.Test/Components/CommentTest.cs, src/TDesign/Components/TComment.cs
* feat:评论组件
* test:评论组件的单元测试
* demo:评论组件的页面展示
> 其他描述写在这里
ISSUE 编号： #3 
=> 【新增】Comment 评论组件

doc/TDesign.Docs.Shared/Layouts/NavMenu.razor, doc/TDesign.Docs.Shared/Pages/Components/InputRangePage.razor, src/TDesign.Test/Components/InputRangeTest.cs, src/TDesign/Components/Forms/TDesignInputComonentBase.cs, src/TDesign/Components/Forms/TInputRange.cs
=> [新增]TInputRange 组件

src/TDesign/TDesign.csproj
=> [feat] 更新版本

doc/TDesign.Docs.Shared/Layouts/NavMenu.razor
>修复 git page 的快速上手 404
> 修改快速上手路径，适应本地和 git page
ISSUE 编号：[#180](https://github.com/AchievedOwner/TDesignBlazor/issues/180)
=> 修复 git page 的快速上手 404

readme.md
>标题格式：
修复主页描述
修复 readme.md 引入Css 错误
增加引入js
ISSUE 编号： #190
无
=> fixBug readme.md

.github/workflows/pull-request.yml
=> fix: pull-request 加判断条件触发

.github/release-drafter.yml
=> bugfix(ci): 更新 release-drafter.yml

doc/TDesign.Docs.Shared/Layouts/MainLayout.razor, doc/TDesign.Docs.Shared/wwwroot/app.css, src/TDesign/TDesignExtensions.cs, src/TDesign/wwwroot/tdesign-blazor.js
提供暗黑和浅色模式切换的功能 `JS.ThemeModeChange(bool isDark)`
组件的暗黑模式看起来效果都还不错。
演示站点暗黑模式需要修改 CSS 以适配，因演示站点界面尚存在问题，需要后续处理。
https://github.com/AchievedOwner/TDesignBlazor/issues/188
=> feat: 新增暗黑和浅色模式切换

.github/release-drafter.yml, doc/TDesign.Docs.Shared/Components/ComponentAPI.razor, doc/TDesign.Docs.Shared/Layouts/MainLayout.razor, doc/TDesign.Docs.Shared/Layouts/NavMenu.razor, doc/TDesign.Docs.Shared/Pages/Components/PopConfirmPage.razor, doc/TDesign.Docs.Shared/Pages/Components/PopupPage.razor, doc/TDesign.Docs.Shared/Pages/Components/TooltipPage.razor, src/TDesign/Components/Popup/PopperOptions.cs, src/TDesign/Components/Popup/TPopup.cs, src/TDesign/Components/TButton.cs, src/TDesign/Components/TPopConfirm.cs, src/TDesign/Components/TTooltip.cs, src/TDesign/Enum/Theme.cs, src/TDesign/TDesignComponentBase.cs
fix(docs): 调整 API 文档的显示高度
Closing #14
=> feat: 新增 TPopConfirm 气泡对话框组件

.github/workflows/deploy-webassembl-artifact.yml, .github/workflows/git-pages-ci.yml, .gitignore
=> feat(ci): 新增部署到 Serverless 的脚本

readme.md
=> docs: 许可证链接错误，访问404

doc/TDesign.Docs.Shared/Layouts/MainLayout.razor
=> docs: 页脚增加网站域名备案号显示

readme.md
=> docs: 修改了 readme.md 在线演示站点的链接，不再使用github pages

doc/TDesign.Docs.Shared/Layouts/MainLayout.razor, doc/TDesign.Docs.Shared/wwwroot/app.css
滚动条、header边框、主题切换按钮细节、t-layout__content整体背景颜色切换
对比图：
=> chore: 预览站点优化页面样式

doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Pages/Components/TablePage.razor, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, src/TDesign/Components/Table/TTable.cs
=> feat: 组件table强化，增加（基础的）加载状态

doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Pages/Components/Data/TablePage.razor, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, src/TDesign.Test/Components/Data/TableTest.cs, src/TDesign/Components/Table/TTable.cs
=> feat: TTable 增加 EmptyContent 参数支持空数据模板

TDesign.sln, doc/TDesign.Docs.ServerSide/Pages/_Host.cshtml, doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Pages/Components/Data/TablePage.razor, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, src/TDesign.Test/Components/Data/TableTest.cs, src/TDesign/Components/Table/TTable.build.cs, src/TDesign/Components/Table/TTable.cs, src/TDesign/Components/Table/TTable.method.cs, src/TDesign/Components/Table/TTableColumnBase.cs, src/TDesign/Components/Table/TTableFieldColumn.cs
=> feat: TTable 的自定义表底功能

doc/TDesign.Docs.Shared/wwwroot/app.css, doc/TDesign.Docs.Shared/wwwroot/styles-github.min.css
1. 重复滚动条样式代码合并
2. 暗色模式代码边框和样式修正
=> chore: 代码高亮暗色主题

doc/TDesign.Docs.Shared/Layouts/LayoutContent.razor
https://github.com/AchievedOwner/TDesignBlazor/issues/239
=> fix: AdditionalStyle 改为 style 使 fixed 样式其生效

doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Pages/Components/Data/TablePage.razor, doc/TDesign.Docs.Shared/Pages/TestPage.razor, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, src/TDesign/Components/Table/EvetArgs/TTableRowItemEventArgs.cs, src/TDesign/Components/Table/TTable.cs, src/TDesign/Components/Table/TTable.method.cs, src/TDesign/Components/Table/TTableCheckboxColumn.cs, src/TDesign/Components/Table/TTableColumnBase.cs, src/TDesign/Components/Table/TTableRadioColumn.cs
=> feat(TTable): 增加 TTableCheckboxColumn 复选框的列

doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Pages/TestPage.razor, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, src/TDesign/Components/Popup/Popper.cs, src/TDesign/Components/Popup/PopperExtensions.cs, src/TDesign/Components/Popup/PopperOptions.cs, src/TDesign/Components/Popup/TPopup.cs, src/TDesign/TDesignExtensions.cs, src/TDesign/TDesignOptions.cs, src/TDesign/wwwroot/tdesign-blazor.js
=> fix(TPopup): 修复闪动显示的问题

src/TDesign/wwwroot/tdesign-blazor.js
=> fix(TPopup): 弹出位置显示不正确

TDesign.sln, doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Components/ComponentAPI.razor, doc/TDesign.Docs.Shared/Layouts/NavMenu.razor, doc/TDesign.Docs.Shared/Pages/Components/Input/InputTagPage.razor, doc/TDesign.Docs.Shared/Pages/TestPage.razor, doc/TDesign.Docs.Shared/wwwroot/app.css, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, src/TDesign/Components/Forms/TDesignInputComonentBase.cs, src/TDesign/Components/Forms/TForm.cs, src/TDesign/Components/Forms/TInputTag.cs, src/TDesign/Components/Menu/TMenuItem.cs, src/TDesign/Components/TTag.cs, src/TDesign/Components/Table/TTable.build.cs, src/TDesign/TDesign.csproj, src/TDesign/TDesignExtensions.cs, src/TDesign/Using.cs, src/TDesign/wwwroot/tdesign-blazor.js
=> feat(TTagInput): 新增 TTagInput 组件

doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Pages/Components/Data/LoadingPage.razor, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, src/TDesign/Components/Loading/TLoading.cs
=> feat(TLoading): 移除 TLoading 组件的 Visible 双向绑定功能

src/TDesign/Components/Dialog/DialogWrapper.cs, src/TDesign/Components/Dialog/Templates/ConfirmationDialogTemplate.cs, src/TDesign/Components/Dialog/Templates/MessageDialogTemplate.cs, src/TDesign/Components/Forms/TInputTag.cs, src/TDesign/Components/TPagination.cs, src/TDesign/Components/TPopConfirm.cs, src/TDesign/Components/Table/TTable.build.cs, src/TDesign/Components/Table/TTableCheckboxColumn.cs, src/TDesign/Components/Timeline/TTimelineItem.cs, src/TDesign/TDesign.csproj
=> refactor: 升级 ComponentBuilder 到 4.1

doc/TDesign.Docs.Shared/Pages/TestPage.razor, src/TDesign/Components/TPagination.cs
=> fix(TPagination): 修复总页数小于2页时的分页条显示错误

doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Pages/Components/Notification/AlertPage.razor, doc/TDesign.Docs.Shared/Pages/Components/Notification/NotificationPage.razor, doc/TDesign.Docs.Shared/Pages/Startup/DesignPage.razor, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, src/TDesign.Test/Components/Notification/AlertTest.cs, src/TDesign/Components/Notify/Abstractions/NotifyComponentBase.cs, src/TDesign/Components/Notify/Messages/TMessage.cs, src/TDesign/Components/Notify/Notification/TNotification.cs, src/TDesign/Components/TAlert.cs, src/TDesign/Interceptors/SpecificationInterceptor.cs
=> fix(TAlert): 图标无法对齐的问题

Contributing.md, doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Pages/TestPage.razor, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, readme.md, src/TDesign/Components/Menu/TMenuItem.cs
=> fix(TMenuItem): 菜单无法根据导航的变化自动高亮

Contributing.md
=> docs(Contributing):更新了贡献文档

doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Pages/Components/Basic/ButtonPage.razor, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, src/TDesign.Test/Components/Basic/ButtonTest.cs, src/TDesign/Components/TButton.cs
=> feat(TButton): 按钮支持图标和文本的效果

doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Pages/Components/Basic/ButtonPage.razor, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, src/TDesign.Test/Components/Basic/ButtonTest.cs, src/TDesign/Components/TButton.cs
=> feat(TButton): 自定义标记渲染的按钮

doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Layouts/NavMenu.razor, doc/TDesign.Docs.Shared/Pages/Components/Navigation/DropdownPage.razor, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, src/TDesign/Abstractions/FragmentContent.cs, src/TDesign/Components/Dropdown/Dropdown.cs, src/TDesign/Components/Dropdown/DropdownOption.cs, src/TDesign/Components/Dropdown/TDropdown.cs, src/TDesign/Components/Popup/TPopup.cs
=> feat(TDropdown): 下拉菜单组件

doc/TDesign.Docs.ServerSide/TDesign.xml, doc/TDesign.Docs.Shared/Layouts/NavMenu.razor, doc/TDesign.Docs.Shared/Pages/Components/Data/CalendarPage.razor, doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml, src/TDesign/Components/TCalendar.cs
=> feat(TCalendar):  新增 TCalendar 日历控件

doc/TDesign.Docs.Shared/Components/PageLayout.razor, doc/TDesign.Docs.Shared/Layouts/MainLayout.razor, doc/TDesign.Docs.Shared/Pages/Components/Data/CardPage.razor, doc/TDesign.Docs.Shared/Pages/Components/Data/TooltipPage.razor, doc/TDesign.Docs.Shared/Pages/Components/Input/InputTextAreaPage.razor, doc/TDesign.Docs.Shared/Pages/Components/Input/SwitchPage.razor, doc/TDesign.Docs.Shared/Pages/Components/Notification/PopConfirmPage.razor, doc/TDesign.Docs.Shared/Pages/Components/Notification/PopupPage.razor, src/TDesign/Components/Popup/PopperExtensions.cs, src/TDesign/wwwroot/tdesign-blazor.css, yarn.lock
=> fix(TInputText): 提示飘走的问题
